--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

-- Started on 2025-12-14 14:50:22

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 41257)
-- Name: Halls; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Halls" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Capacity" integer NOT NULL
);


ALTER TABLE public."Halls" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 41256)
-- Name: Halls_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Halls" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Halls_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 41265)
-- Name: Movies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Movies" (
    "Id" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "DurationMinutes" integer NOT NULL,
    "AgeLimit" integer NOT NULL
);


ALTER TABLE public."Movies" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 41264)
-- Name: Movies_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Movies" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Movies_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 41273)
-- Name: Sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Sessions" (
    "Id" integer NOT NULL,
    "MovieId" integer NOT NULL,
    "HallId" integer NOT NULL,
    "StartTime" timestamp with time zone NOT NULL,
    "TicketPrice" numeric NOT NULL
);


ALTER TABLE public."Sessions" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 41272)
-- Name: Sessions_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Sessions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Sessions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 41291)
-- Name: Tickets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tickets" (
    "Id" integer NOT NULL,
    "SessionId" integer NOT NULL,
    "SeatNumber" integer NOT NULL,
    "CustomerName" text NOT NULL,
    "PurchaseTime" timestamp with time zone NOT NULL
);


ALTER TABLE public."Tickets" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 41290)
-- Name: Tickets_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Tickets" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tickets_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 41251)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 4814 (class 0 OID 41257)
-- Dependencies: 217
-- Data for Name: Halls; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Halls" ("Id", "Name", "Capacity") FROM stdin;
3	Hall 1	10
4	Hall 2	30
\.


--
-- TOC entry 4816 (class 0 OID 41265)
-- Dependencies: 219
-- Data for Name: Movies; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Movies" ("Id", "Title", "Description", "DurationMinutes", "AgeLimit") FROM stdin;
1	Dune: Part Two	Epic sci-fi	166	0
2	Inception	Dream within a dream	148	0
\.


--
-- TOC entry 4818 (class 0 OID 41273)
-- Dependencies: 221
-- Data for Name: Sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Sessions" ("Id", "MovieId", "HallId", "StartTime", "TicketPrice") FROM stdin;
9	1	3	2025-12-14 14:41:03.125+02	0
10	2	3	2026-12-14 14:41:03.125+02	0
\.


--
-- TOC entry 4820 (class 0 OID 41291)
-- Dependencies: 223
-- Data for Name: Tickets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Tickets" ("Id", "SessionId", "SeatNumber", "CustomerName", "PurchaseTime") FROM stdin;
1	10	5	Ria	2025-12-14 14:42:44.887876+02
\.


--
-- TOC entry 4812 (class 0 OID 41251)
-- Dependencies: 215
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20251127231631_InitialCreate	9.0.0
\.


--
-- TOC entry 4826 (class 0 OID 0)
-- Dependencies: 216
-- Name: Halls_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Halls_Id_seq"', 6, true);


--
-- TOC entry 4827 (class 0 OID 0)
-- Dependencies: 218
-- Name: Movies_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Movies_Id_seq"', 4, true);


--
-- TOC entry 4828 (class 0 OID 0)
-- Dependencies: 220
-- Name: Sessions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Sessions_Id_seq"', 10, true);


--
-- TOC entry 4829 (class 0 OID 0)
-- Dependencies: 222
-- Name: Tickets_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Tickets_Id_seq"', 1, true);


--
-- TOC entry 4656 (class 2606 OID 41263)
-- Name: Halls PK_Halls; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Halls"
    ADD CONSTRAINT "PK_Halls" PRIMARY KEY ("Id");


--
-- TOC entry 4658 (class 2606 OID 41271)
-- Name: Movies PK_Movies; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Movies"
    ADD CONSTRAINT "PK_Movies" PRIMARY KEY ("Id");


--
-- TOC entry 4662 (class 2606 OID 41279)
-- Name: Sessions PK_Sessions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sessions"
    ADD CONSTRAINT "PK_Sessions" PRIMARY KEY ("Id");


--
-- TOC entry 4665 (class 2606 OID 41297)
-- Name: Tickets PK_Tickets; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tickets"
    ADD CONSTRAINT "PK_Tickets" PRIMARY KEY ("Id");


--
-- TOC entry 4654 (class 2606 OID 41255)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4659 (class 1259 OID 41303)
-- Name: IX_Sessions_HallId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Sessions_HallId" ON public."Sessions" USING btree ("HallId");


--
-- TOC entry 4660 (class 1259 OID 41304)
-- Name: IX_Sessions_MovieId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Sessions_MovieId" ON public."Sessions" USING btree ("MovieId");


--
-- TOC entry 4663 (class 1259 OID 41305)
-- Name: IX_Tickets_SessionId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tickets_SessionId" ON public."Tickets" USING btree ("SessionId");


--
-- TOC entry 4666 (class 2606 OID 41280)
-- Name: Sessions FK_Sessions_Halls_HallId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sessions"
    ADD CONSTRAINT "FK_Sessions_Halls_HallId" FOREIGN KEY ("HallId") REFERENCES public."Halls"("Id") ON DELETE CASCADE;


--
-- TOC entry 4667 (class 2606 OID 41285)
-- Name: Sessions FK_Sessions_Movies_MovieId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sessions"
    ADD CONSTRAINT "FK_Sessions_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES public."Movies"("Id") ON DELETE CASCADE;


--
-- TOC entry 4668 (class 2606 OID 41298)
-- Name: Tickets FK_Tickets_Sessions_SessionId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tickets"
    ADD CONSTRAINT "FK_Tickets_Sessions_SessionId" FOREIGN KEY ("SessionId") REFERENCES public."Sessions"("Id") ON DELETE CASCADE;


-- Completed on 2025-12-14 14:50:22

--
-- PostgreSQL database dump complete
--

